#!/usr/bin/env bash
# Install nginx web server

sudo apt update
sudo apt install -y nginx
sudo chmod 777 /var/www/html -R
sudo chmod 777 /ect/nginx/sites-available -R
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/listen \[::\]:80 default_server;/a rewrite ^/redirect_me/(.*) https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /ect/nginx/sites-available/default
sudo service nginx restart
