#!/usr/bin/env bash
# Install nginx web server

sudo apt update
sudo apt install -y nginx
sudo chmod 777 /var/www/html -R
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server;/a rewrite ^/error_page 404 /404.html;' /ect/nginx/sites-available/default
sudo service nginx restart
