#!/usr/bin/env bash
# this is a coment
sudo apt -y update
sudo apt -y install nginx
sudo chmod 777 /etc/nginx/sites-available -R
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
