#!/usr/bin/env bash
# Install nginx web server

Find="^\tlocation / {"
Replace="\terror_page 404 /404.html;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {\n\t\tadd_header X-Served-By '$HOSTNAME';"

sudo apt update
sudo apt install -y nginx
sudo chmod 777 /var/www/html -R
sudo chmod 777 /etc/nginx/sites-available -R
echo "Hello World" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo chmod 777 /var/www/html -R
sed -i "s|$Find|$Replace|" /etc/nginx/sites-available/default
sudo service nginx restart
