#!/usr/bin/env bash
#Install your load balancer

Append="\nfrontend myfrontend\n\tbind :80\n\tdefault_backend myservers\nbackend myservers\n\tbalance roundrobin\n\tserver 4925-web-01 75.101.200.146:80\n\tserver 4925-web-02 54.198.59.168:80"

sudo apt update
sudo apt-get install -y haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
echo -e $Append >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart